eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9411
spring:
  application:
    name: zipkin-server
  rabbitmq:
    host: 192.168.1.130
    port: 5672
    username: admin
    password: admin
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_zipkin?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
zipkin:
  storage:
    type: mysql