eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 5000
spring:
  application:
    name: gateway-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: 192.168.1.130
    port: 5672
    username: admin
    password: admin
zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: user-service